// <auto-generated />
using JamTechSalary.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JaTechSalary.Migrations
{
    [DbContext(typeof(JamTechSalaryDbContext))]
    [Migration("20260301010926_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JamTechSalary.API.Entities.AiTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("AiTool");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("Benefit");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.JobPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobPlatform");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguage");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SkillDevelopmentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("SkillDevelopmentMethod");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SurveyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRange")
                        .HasColumnType("integer");

                    b.Property<int>("BelievesAiWillReplaceRole")
                        .HasColumnType("integer");

                    b.Property<int>("CareerGoal")
                        .HasColumnType("integer");

                    b.Property<string>("CommunityImprovementComment")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("integer");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<int>("JobFindingEase")
                        .HasColumnType("integer");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("MainAreaOfInterest")
                        .HasColumnType("text");

                    b.Property<string>("MissedAspectsComment")
                        .HasColumnType("text");

                    b.Property<string>("Parish")
                        .HasColumnType("text");

                    b.Property<string>("PreferredEmploymentDestination")
                        .HasColumnType("text");

                    b.Property<bool>("ResidesInJamaica")
                        .HasColumnType("boolean");

                    b.Property<int>("SalaryRange")
                        .HasColumnType("integer");

                    b.Property<string>("SideProjectComments")
                        .HasColumnType("text");

                    b.Property<decimal?>("SideProjectEarnings")
                        .HasColumnType("numeric");

                    b.Property<string>("TertiaryInstitution")
                        .HasColumnType("text");

                    b.Property<string>("UniversityMajor")
                        .HasColumnType("text");

                    b.Property<bool>("UsesAiTools")
                        .HasColumnType("boolean");

                    b.Property<int>("WorkLocation")
                        .HasColumnType("integer");

                    b.Property<string>("WorkPlace")
                        .HasColumnType("text");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SurveyResponse");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.TechCommunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("TechCommunity");
                });

            modelBuilder.Entity("JobPlatformSurveyResponse", b =>
                {
                    b.Property<int>("JobFindingPlatformsId")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyResponseId")
                        .HasColumnType("integer");

                    b.HasKey("JobFindingPlatformsId", "SurveyResponseId");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("SurveyJobFindingPlatforms", (string)null);
                });

            modelBuilder.Entity("JobPlatformSurveyResponse1", b =>
                {
                    b.Property<int>("JobSearchPlatformsId")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyResponse1Id")
                        .HasColumnType("integer");

                    b.HasKey("JobSearchPlatformsId", "SurveyResponse1Id");

                    b.HasIndex("SurveyResponse1Id");

                    b.ToTable("SurveyJobSearchingPlatforms", (string)null);
                });

            modelBuilder.Entity("ProgrammingLanguageSurveyResponse", b =>
                {
                    b.Property<int>("CurrentLanguagesId")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyResponseId")
                        .HasColumnType("integer");

                    b.HasKey("CurrentLanguagesId", "SurveyResponseId");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("SurveyCurrentLanguages", (string)null);
                });

            modelBuilder.Entity("ProgrammingLanguageSurveyResponse1", b =>
                {
                    b.Property<int>("PlannedLanguagesId")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyResponse1Id")
                        .HasColumnType("integer");

                    b.HasKey("PlannedLanguagesId", "SurveyResponse1Id");

                    b.HasIndex("SurveyResponse1Id");

                    b.ToTable("SurveyPlannedLanguages", (string)null);
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.AiTool", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("AiToolsUsed")
                        .HasForeignKey("SurveyResponseId");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.Benefit", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("Benefits")
                        .HasForeignKey("SurveyResponseId");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SkillDevelopmentMethod", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("SkillDevelopmentMethods")
                        .HasForeignKey("SurveyResponseId");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SurveyResponse", b =>
                {
                    b.OwnsOne("JamTechSalary.API.Entities.LayoffRecord", "Layoff", b1 =>
                        {
                            b1.Property<int>("SurveyResponseId")
                                .HasColumnType("integer");

                            b1.Property<string>("CompanyName")
                                .HasColumnType("text");

                            b1.Property<bool>("WasLaidOff")
                                .HasColumnType("boolean");

                            b1.HasKey("SurveyResponseId");

                            b1.ToTable("SurveyResponse");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResponseId");
                        });

                    b.OwnsOne("JamTechSalary.API.Entities.PromotionRecord", "Promotion", b1 =>
                        {
                            b1.Property<int>("SurveyResponseId")
                                .HasColumnType("integer");

                            b1.Property<string>("PromotedToRole")
                                .HasColumnType("text");

                            b1.Property<bool>("WasPromoted")
                                .HasColumnType("boolean");

                            b1.HasKey("SurveyResponseId");

                            b1.ToTable("SurveyResponse");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResponseId");
                        });

                    b.OwnsOne("JamTechSalary.API.Entities.SalaryIncreaseRecord", "SalaryIncrease", b1 =>
                        {
                            b1.Property<int>("SurveyResponseId")
                                .HasColumnType("integer");

                            b1.Property<string>("IncreasePercentageBand")
                                .HasColumnType("text");

                            b1.Property<bool>("ReceivedIncrease")
                                .HasColumnType("boolean");

                            b1.HasKey("SurveyResponseId");

                            b1.ToTable("SurveyResponse");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResponseId");
                        });

                    b.Navigation("Layoff")
                        .IsRequired();

                    b.Navigation("Promotion")
                        .IsRequired();

                    b.Navigation("SalaryIncrease")
                        .IsRequired();
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.TechCommunity", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("TechCommunities")
                        .HasForeignKey("SurveyResponseId");
                });

            modelBuilder.Entity("JobPlatformSurveyResponse", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.JobPlatform", null)
                        .WithMany()
                        .HasForeignKey("JobFindingPlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany()
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobPlatformSurveyResponse1", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.JobPlatform", null)
                        .WithMany()
                        .HasForeignKey("JobSearchPlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany()
                        .HasForeignKey("SurveyResponse1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProgrammingLanguageSurveyResponse", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.ProgrammingLanguage", null)
                        .WithMany()
                        .HasForeignKey("CurrentLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany()
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProgrammingLanguageSurveyResponse1", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.ProgrammingLanguage", null)
                        .WithMany()
                        .HasForeignKey("PlannedLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany()
                        .HasForeignKey("SurveyResponse1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SurveyResponse", b =>
                {
                    b.Navigation("AiToolsUsed");

                    b.Navigation("Benefits");

                    b.Navigation("SkillDevelopmentMethods");

                    b.Navigation("TechCommunities");
                });
#pragma warning restore 612, 618
        }
    }
}
