// <auto-generated />
using JamTechSalary.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaTechSalary.Migrations
{
    [DbContext(typeof(JamTechSalaryDbContext))]
    [Migration("20260228182326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JamTechSalary.API.Entities.AiTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("AiTool");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("Benefit");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.JobPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyResponseId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.HasIndex("SurveyResponseId1");

                    b.ToTable("JobPlatform");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyResponseId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.HasIndex("SurveyResponseId1");

                    b.ToTable("ProgrammingLanguage");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SkillDevelopmentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("SkillDevelopmentMethod");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SurveyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgeRange")
                        .HasColumnType("int");

                    b.Property<int>("BelievesAiWillReplaceRole")
                        .HasColumnType("int");

                    b.Property<int>("CareerGoal")
                        .HasColumnType("int");

                    b.Property<string>("CommunityImprovementComment")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .HasColumnType("longtext");

                    b.Property<int>("JobFindingEase")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("MainAreaOfInterest")
                        .HasColumnType("longtext");

                    b.Property<string>("MissedAspectsComment")
                        .HasColumnType("longtext");

                    b.Property<string>("Parish")
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredEmploymentDestination")
                        .HasColumnType("longtext");

                    b.Property<bool>("ResidesInJamaica")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SalaryRange")
                        .HasColumnType("int");

                    b.Property<string>("SideProjectComments")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SideProjectEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TertiaryInstitution")
                        .HasColumnType("longtext");

                    b.Property<string>("UniversityMajor")
                        .HasColumnType("longtext");

                    b.Property<bool>("UsesAiTools")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WorkLocation")
                        .HasColumnType("int");

                    b.Property<string>("WorkPlace")
                        .HasColumnType("longtext");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SurveyResponse");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.TechCommunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SurveyResponseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.ToTable("TechCommunity");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.AiTool", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("AiToolsUsed")
                        .HasForeignKey("SurveyResponseId");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.Benefit", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("Benefits")
                        .HasForeignKey("SurveyResponseId");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.JobPlatform", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("JobFindingPlatforms")
                        .HasForeignKey("SurveyResponseId");

                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("JobSearchPlatforms")
                        .HasForeignKey("SurveyResponseId1");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.ProgrammingLanguage", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("CurrentLanguages")
                        .HasForeignKey("SurveyResponseId");

                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("PlannedLanguages")
                        .HasForeignKey("SurveyResponseId1");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SkillDevelopmentMethod", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("SkillDevelopmentMethods")
                        .HasForeignKey("SurveyResponseId");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SurveyResponse", b =>
                {
                    b.OwnsOne("JamTechSalary.API.Entities.LayoffRecord", "Layoff", b1 =>
                        {
                            b1.Property<int>("SurveyResponseId")
                                .HasColumnType("int");

                            b1.Property<string>("CompanyName")
                                .HasColumnType("longtext");

                            b1.Property<bool>("WasLaidOff")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("SurveyResponseId");

                            b1.ToTable("SurveyResponse");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResponseId");
                        });

                    b.OwnsOne("JamTechSalary.API.Entities.PromotionRecord", "Promotion", b1 =>
                        {
                            b1.Property<int>("SurveyResponseId")
                                .HasColumnType("int");

                            b1.Property<string>("PromotedToRole")
                                .HasColumnType("longtext");

                            b1.Property<bool>("WasPromoted")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("SurveyResponseId");

                            b1.ToTable("SurveyResponse");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResponseId");
                        });

                    b.OwnsOne("JamTechSalary.API.Entities.SalaryIncreaseRecord", "SalaryIncrease", b1 =>
                        {
                            b1.Property<int>("SurveyResponseId")
                                .HasColumnType("int");

                            b1.Property<string>("IncreasePercentageBand")
                                .HasColumnType("longtext");

                            b1.Property<bool>("ReceivedIncrease")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("SurveyResponseId");

                            b1.ToTable("SurveyResponse");

                            b1.WithOwner()
                                .HasForeignKey("SurveyResponseId");
                        });

                    b.Navigation("Layoff")
                        .IsRequired();

                    b.Navigation("Promotion")
                        .IsRequired();

                    b.Navigation("SalaryIncrease")
                        .IsRequired();
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.TechCommunity", b =>
                {
                    b.HasOne("JamTechSalary.API.Entities.SurveyResponse", null)
                        .WithMany("TechCommunities")
                        .HasForeignKey("SurveyResponseId");
                });

            modelBuilder.Entity("JamTechSalary.API.Entities.SurveyResponse", b =>
                {
                    b.Navigation("AiToolsUsed");

                    b.Navigation("Benefits");

                    b.Navigation("CurrentLanguages");

                    b.Navigation("JobFindingPlatforms");

                    b.Navigation("JobSearchPlatforms");

                    b.Navigation("PlannedLanguages");

                    b.Navigation("SkillDevelopmentMethods");

                    b.Navigation("TechCommunities");
                });
#pragma warning restore 612, 618
        }
    }
}
